### ISSUE TITLE
Ground link

### ISSUE THREAD

**Issue by horverno** [szenergy/nissan_leaf_ros#3]
TF or param to get an exact Z position of all the vehicles.
This is needed in the barrier detection, but later may other algorithms will use it.
(Request from KP)

https://github.com/szenergy/szenergy-public-resources/wiki/H-TF
https://github.com/szenergy/nissan_leaf_ros/blob/master/nissan_bringup/launch/sensory/car_parameters_leaf.launch

**Comment by gfigneczi1** [comment]
Itt csak szoftver módosításra van szükség (lekérdezni pl current_pose-ból), vagy valami számolásra is? Ez elérhető GPS adat, nem?

**Comment by horverno** [comment]
csak sima szoftveres módosítás, közben Mikivel meg is beszéltük, hogy nem plusz param lesz, hanem a TF-be kerüljön fixen (a `groud_link` amúgy többi járműnél is létezzen kompatibiltási okokból)
