### ISSUE TITLE
 sensor-description

### ISSUE THREAD

**Issue by enginksz** [szenergy/nissan_leaf_ros#4]
Hello,

The sensor-description  (nissan_packages.repos) included in the installation cannot be downloaded. Without this repo, can't we see vehicle or sensor outputs on rviz?

What can we do so that we can only see the vehicle and sensors on our vehicle?

thanks

**Comment by horverno** [comment]
hello @enginksz 

first let me aks you what kind of environment are you using? I mean vehicle, sensors, etc. This repo is public and you can use it of curse, but it is very limited to our specific Nissan Leaf vehicle, with LIDAR, GNSS, IMU, camera and a lot of customization. This sytstem is visualized [in this video](https://www.youtube.com/watch?v=vr9agp8W9Oc&ab_channel=JKK-VehicleIndustryResearchCenter).
